name: ReactJs package

on: 
  push: 
    branches: ["test"]
    
jobs: 
  build: 
    runs-on: ubuntu-latest 
    
    steps: 
  
      - uses: actions/checkout@v3 
      
      - name: checking container 
        run: |
          echo I am in container 
          ls -a 
          echo checking java version .....
          java --version
          echo Is git installed.......?
          git --version
          echo Is build tools installed...?
          npm --version
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: $USERNAME
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
#       - name: Build & push Docker image
#         uses: mr-smithers-excellent/docker-build-push@v5
#         with:
#           image: hrc1663/react-js-image
#           tags: latest
#           registry: docker.io
#           dockerfile: Dockerfile
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
